### ISSUE TITLE
info

### ISSUE THREAD

**Issue by devds** [COFFASoft/Coffa-Viewer#3]
Hello, having problems to compile.
Are you avalilable to help me?
Another question : 
I am working with VS c++ 2022 and Qt 6.2.3  ( i saw... 5.12 )
Is it ok?

**Comment by MansourMbow** [comment]
Hello @devds, can you please share the error you're having when compiling?

Using VS 2022 should not prevent from compiling the source (working fine on my side). But the Qt version should at least be changed in the project properties (I'm still using Qt5, don't know much about Qt6 but they should be the same).

Go to Project Properties>Linker>Input and add manually your Qt libs (Qt6xxx.lib). You'll probably need to add:
Qt6Core.lib
Qt6Gui.lib
Qt6Widgets.lib
Qt6Qml.lib

Hope that it helps.
Cheers.
